# Generated by Django 6.0.3 on 2026-04-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visitor_expiry_time_visitor_is_verified_visitor_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
