# Generated by Django 6.0.3 on 2026-04-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_facility_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitybooking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitybooking',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
