# Generated by Django 6.0.3 on 2026-04-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_facilitybooking_end_time_facilitybooking_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(choices=[('Guest', 'Guest'), ('Delivery', 'Delivery'), ('Service', 'Service'), ('Cab', 'Cab')], max_length=20),
        ),
    ]
